### ISSUE TITLE
StrongSwan template

### ISSUE THREAD

**Issue by snobu** [Azure/Azure-vpn-config-samples#10]
Anyone from Microsoft still reading the issues in this repo?

If i submit a StrongSwan IKEv2 template, is that something that could be considered for merging and ultimately showing up in the Azure Portal?

I've also noticed the only template now showing is "Microsoft":
![image](https://cloud.githubusercontent.com/assets/6472374/16243784/97f841b2-3801-11e6-8184-c2079be8dea7.png)

Is the template feature being discontinued or is this just a temporary glitch?

Thank you.

**Comment by effingerw** [comment]
I believe we have a example
