### ISSUE TITLE
Any example for Cisco IOS XE 15.4+?

### ISSUE THREAD

**Issue by nutinshell** [Azure/Azure-vpn-config-samples#11]
IOS XE 15.4+ seems have some issues with 15.2 config example, it keeping create CHILD_SA every minute.

**Comment by bridgetcdavis** [comment]
What SA timeout settings do you have?

**Comment by nutinshell** [comment]
@bridgetcdavis you mean SA lifetime? it's 86400.

**Comment by bridgetcdavis** [comment]
@nutinshell If you have a Policy-based gateway, your lifetime needs to be set to 28,800 seconds. If you have a Route-based gateway, your lifetime needs to be set to 10,800 seconds. Please let me know if this doesn't fix the issue.
For more IPsec parameter information, see https://azure.microsoft.com/en-us/documentation/articles/vpn-gateway-about-vpn-devices/.
