### ISSUE TITLE
Is this sample for both RouteBased and PolicyBased?

### ISSUE THREAD

**Issue by KazuhikoKondo** [Azure/Azure-vpn-config-samples#18]
According to the following page, both RouteBased and PolicyBased for Juniper SRX is navigated to this page.  Is the configuration same of both?
https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-devices

It seems this page is for RouteBased.  Does Juniper SRX support PolicyBased?

**Comment by Aviky** [comment]
+1

**Comment by KazuhikoKondo** [comment]
I had a chance to talk with Juniper team offline, and I got the answer.
- Juniper SRX supports both RouteBased and PolicyBased.
- Regarding the configuration of PolicyBased, see the following page.
https://www.juniper.net/documentation/en_US/junos/topics/example/ipsec-policy-based-vpn-configuring.html
