### ISSUE TITLE
UTF-16 forces git to treat .cfg as binary

### ISSUE THREAD

**Issue by snobu** [Azure/Azure-vpn-config-samples#4]
Do we really need `UTF-16` here?

https://github.com/Azure/Azure-vpn-config-samples/blob/master/Cisco/cisco-isr-ios-15.1-dynamic-routing.cfg#L1

``` xml
<?xml version="1.0" encoding="utf-16"?>
```

Forces git to treat .cfg files as binary.

**Comment by Larrykuntz10** [comment]
Notice the quick response from Microsoft.

**Comment by effingerw** [comment]
moved everything to markdown thanks for your feedback
