### ISSUE TITLE
IP scheme used in the example.

### ISSUE THREAD

**Issue by stetski1** [Azure/Azure-vpn-config-samples#7]
Hello,
i seen in the example that the tunnel interface was 169.254.0.1 255.255.255.0, please can you confirm that this is just an example and the actual ip address allocated is different.
I would need to know what to target the far end in order to test the ipsec tunnel works.
thanks.

**Comment by ganesr** [comment]
This IP address is on your router for the tunnel interface. You can actually use the sample as is and things will work. You can replace it with a valid IP address from your network if you want. That is absolutely ok.

**Comment by stetski1** [comment]
thanks for the quick response ganesr, but surely i need an ip the other end.
what if i have 3 tunnels, are you saying i could use an arbitary ip address and it would still work ?
how could i test ip to ip connectivity ?

**Comment by ganesr** [comment]
what exactly are you trying to do? You can use 3 different IP addresses in case you have 3 tunnels.

**Comment by stetski1** [comment]
ok, ususally with ipsec / gre, you would use a /32 address to form a point to point tunnel.
and point the LAN traffic down that tunnel. In order to do that, we would need the ip address of the azure side. However the example only gives an example and you say you can use any tunnel ip address. So how would you verify ?
ie - tunnel 1 192.168.1.1 / 32 - to verify ping 192.168.1.2 - azzure side.
how can you verify if the azure side has no ip address ?

**Comment by stetski1** [comment]
sorry, i meant ie - tunnel 1 192.168.1.1 / 30 - to verify ping 192.168.1.2 - azzure side
