### ISSUE TITLE
IP scheme used in the example.

### ISSUE THREAD

**Issue by stetski1** [Azure/Azure-vpn-config-samples#8]
I see the other one was closed, but i still need more information.
Lets take the example of 169.254.0.1. How do i test that the ipsec tunnel is working if i could actually use any ip address. Eg. what would i ping ?
If i had another tunnel on the same router, i couldnt use the same ip, are you saying i can pick any ip and it just works. In that case how do i verify it. Please dont just close the issue as more dialogue will follow. thanks.

**Comment by effingerw** [comment]
Ping by default in Azure is disabled on Azure vm's so you first would want to use [psping ](https://technet.microsoft.com/en-us/sysinternals/psping) or some other tool. Next you would psping from on prem address non [APIPA ](https://tools.ietf.org/html/rfc3927)to an Azure vnet vm ip address 

example:
 My on prem computer is 192.168.1.11 and my Azure VM is 10.1.0.1 on both firewalls have 5555 open
from my on prem pc i run 

azureVM i run psping.exe -s 10.1.0.1:5555 -f
onprem computer psping.exe -t 10.1.0.1:5555
